### ISSUE TITLE
Los Angeles Meetup Thoughts: Summary compatibility

### ISSUE THREAD

**Issue by NoahTheDuke** [NoahTheDuke/lazytest#2]
From the [slack channel](https://clojurians.slack.com/archives/C07NJRDQWDS/p1731560606393509):

> And a question about summary compatibility, `clojure.test` produces a hash map with `:test`, `:pass``, :fail`, and `:error`; lazytest produces a hash map with `:total`, `:pass`, and `:fail`. With the former, `:test` is the number of tests, not assertions (which is the total of pass + fail + error). With the latter, is `:total` the sum of pass + fail? And I assume a test that throws an exception is just treated as a failure (whereas `clojure.test` draws a distinction between failing tests and throwing tests)?

Which is to say, what do the entries mean? How do they match up with clojure.test's entries? Is there a way to make them match up?

**Comment by seancorfield** [comment]
I think it's fine to have the difference in summary, since LazyTest has a different notion of "how many tests/test suites" anyway. `merge-with +` is a decent way to handle the aggregation and produces what I need. `:pass` / `:fail` is the important part (`:error` is "fail-with-exception" in `clojure.test`-land).

I think this can be closed with no action needed.
