### ISSUE TITLE
Los Angeles Meetup Thoughts: `:test` metadata overlaps with clojure.test

### ISSUE THREAD

**Issue by NoahTheDuke** [NoahTheDuke/lazytest#4]
From the [slack channel](https://clojurians.slack.com/archives/C07NJRDQWDS/p1731566136244109):

> However, I've noticed that when you do `(lazytest.repl/run-tests *ns*)` it seems to somehow run `clojure.test` tests as well, report that they fail, but then consider them passes (b/c they didn't throw an exception?). But I'm puzzled as to why it's even trying to run them? They don't have `:type :lazytest/var` (or any other `:type` metadata that lazytest might care about)?

**Comment by seancorfield** [comment]
This makes it very difficult to mix `clojure.test` and LazyTest since `clojure.test` tests are "seen" by LazyTest and executed -- but always pass (because they do not throw exceptions). Running both sets of tests and merging the result summaries is not possible until LazyTest stops trying to run `clojure.test` tests -- this is a blocker for me to even try LazyTest at work.

**Comment by NoahTheDuke** [comment]
Given the lack of current users, I feel safe in switching this mechanism from `:test` to `:lazytest/test`. See [this commit](https://github.com/NoahTheDuke/lazytest/commit/5828b2885fb4a7185bcb5b97c392204a7896134d).

**Comment by onetom** [comment]
i guess, i came late to the party, but to sow the seeds of better naming practices, so we can avoid so much stutter-like word duplications, here are some alternatives:

# `:lazytest/def`

i think this would make a lot of sense, since it's kinda synonymous with `defdescribe`,
plus, if u read it out aloud, like "lazy test definition", it explains its purpose very well

destructuring it like `(let [{:keys [lazytest/def]} {:lazytest/def 123}] def)` would result in a `def` local binding,
but i don't think that would cause much trouble.

# `:lazytest/spec`

tests are sometimes called as specifications, as `lazytest.core/specify` hints at too,
but the `spec` abbreviation is too much associated with `clojure.spec`, so it's not that great

# `:lazytest/case`

"test case" sounds  good, but since we can specify a suite too, it wouldn't be singular every time

# `:lazytest/suite`

since its value is not always a literal `lazytest.suite.Suite` (duplication again...), it's slightly misleading

**Comment by NoahTheDuke** [comment]
Those are some good suggestions but there are multiple users now relying on the existing name and I'm loathe to break their code.
